# Generated by Django 5.0.1 on 2024-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstructure', '0002_remove_product_image_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
