# Generated by Django 5.0.1 on 2024-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstructure', '0003_remove_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
    ]
